# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

up:
  - homebrew:
    - golangci/tap/golangci-lint
  - go:
      version: 1.17.7
      modules: true

commands:
  build:
    desc: Build the Docker image to run the tests
    run: ./build.sh
  test:
    desc: Runs tests
    run: ./test.sh
  lint:
    desc: Runs golangci-lint
    run: golangci-lint run
